Update strings.po all languages
i96751414/plugin.video.flix pull request #10
Opened 2024-02-18 15:50 UTC by icarok99

2024-02-19 12:25 UTC, i96751414 commented
Thank you. I will have a look as soon as I have some spare time.

2024-02-21 21:44 UTC, i96751414 requested changes
Thanks for the updates. I did a review, and PT-PT strings need update

2024-02-21 21:44 UTC, i96751414 commented on resources/language/resource.language.pt_pt/strings.po
> +msgstr "Tempo de expiração do cache (dias)"
In PT-PT its: cache is female :p
The previous string was correct

2024-02-21 21:44 UTC, i96751414 commented on resources/language/resource.language.pt_pt/strings.po
> +msgstr "Nome do usuário"
PT-PT typically says "utilizador" and not "usuário", please revert.

2024-02-21 21:44 UTC, i96751414 commented on resources/language/resource.language.pt_pt/strings.po
> +msgstr "Obtendo resultados dos provedores..."
Please revert as the previous phrase is more common/used in PT-PT (we usually don't use gerund, specially when starting sentences)

2024-02-21 21:44 UTC, i96751414 commented on resources/language/resource.language.pt_pt/strings.po
> +msgstr "Adicionando conteúdos à biblioteca"
Please revert as the previous phrase is more common/used in PT-PT (we usually don't use gerund, specially when starting sentences)

2024-02-21 21:44 UTC, i96751414 commented on resources/language/resource.language.pt_pt/strings.po
> +msgstr "Atualizando a biblioteca"
Please revert as the previous phrase is more common/used in PT-PT (we usually don't use gerund, specially when starting sentences)

2024-02-21 21:44 UTC, i96751414 commented on resources/language/resource.language.pt_pt/strings.po
> +msgstr "Reconstruindo a biblioteca"
Please revert as the previous phrase is more common/used in PT-PT (we usually don't use gerund, specially when starting sentences)

2024-02-21 21:54 UTC, icarok99 commented
@i96751414 revestir

Essas foram os únicos que mudei

msgctxt "#30018"
msgid "Show unaired episodes"
msgstr "Exibir episódios não emitidos"

msgctxt "#30019"
msgid "Show special episodes"
msgstr "Exibir episódios especiais"

2024-02-25 18:02 UTC, i96751414 approved these changes

2024-02-25 18:03 UTC, i96751414 commented
Can you squash before I merge, please?

2024-02-25 19:13 UTC, icarok99 commented
> Can you squash before I merge, please?

It's you who has to do this by choosing the 2nd option.

2024-02-25 19:29 UTC, i96751414 commented
I think that by doing that I'll remove your name from the contributions as it assumes it was me doing things. But I'll give it a try

2024-02-25 19:30 UTC, merged

2024-02-25 19:43 UTC, icarok99 commented
Remove no 

![Screenshot_2024-02-25-16-43-07-922_com android chrome](https://github.com/i96751414/plugin.video.flix/assets/46580318/4ddde38e-a66a-44ef-a15d-577fcc389dc9)